#!/usr/bin/env python3
from pathlib import Path
from html.parser import HTMLParser
from collections import Counter
import re, subprocess, sys
ROOT = Path(__file__).resolve().parents[1]

class Parser(HTMLParser):
    def __init__(self):
        super().__init__(); self.ids=[]; self.refs=[]; self.scripts=[]
    def handle_starttag(self, tag, attrs):
        d=dict(attrs)
        if d.get('id'): self.ids.append(d['id'])
        for attr in ('src','href'):
            v=d.get(attr)
            if v and not re.match(r'^(?:https?:)?//|^(?:data|blob):',v): self.refs.append(v.split('?')[0].lstrip('./'))
        if tag=='script' and d.get('src','').startswith('assets/js/'): self.scripts.append(d['src'])

def die(msg):
    print('FAIL:',msg); sys.exit(1)

html=(ROOT/'index.html').read_text(encoding='utf-8')
p=Parser(); p.feed(html)
dup_ids=[k for k,v in Counter(p.ids).items() if v>1]
if dup_ids: die('Duplicate HTML IDs: '+', '.join(dup_ids))
missing_refs=[r for r in p.refs if not (ROOT/r).exists()]
if missing_refs: die('Missing HTML resources: '+', '.join(missing_refs))

js_files=sorted((ROOT/'assets/js').glob('*.js'))
for f in js_files+[ROOT/'service-worker.js']:
    subprocess.run(['node','--check',str(f)],check=True,stdout=subprocess.DEVNULL)
js='\n'.join(f.read_text(encoding='utf-8',errors='ignore') for f in js_files)
ids=set(p.ids)
domrefs=set(re.findall(r'(?:getElementById|byId)\([\'\"]([^\'\"]+)[\'\"]\)',js))
missing_dom=sorted(domrefs-ids)
if missing_dom: die('Missing literal DOM IDs: '+', '.join(missing_dom))
fn=[]
for f in js_files: fn += re.findall(r'\bfunction\s+([A-Za-z_$][\w$]*)\s*\(',f.read_text(encoding='utf-8',errors='ignore'))
dup_fn=[k for k,v in Counter(fn).items() if v>1]
if dup_fn: die('Duplicate named functions: '+', '.join(dup_fn))

sw=(ROOT/'service-worker.js').read_text(encoding='utf-8')
block=re.search(r'const APP_SHELL = \[(.*?)\];',sw,re.S)
if not block: die('Cannot find Service Worker APP_SHELL')
app_shell=re.findall(r"['\"](\./[^'\"]+)['\"]",block.group(1))
missing_shell=[]
for ref in app_shell:
    rel=ref[2:]
    if rel and not (ROOT/rel).exists(): missing_shell.append(ref)
if missing_shell: die('Missing APP_SHELL resources: '+', '.join(missing_shell))
state=(ROOT/'assets/js/01-state.js').read_text(encoding='utf-8')
sv=re.search(r"const APP_VERSION = '([^']+)'",state).group(1)
wv=re.search(r"const APP_VERSION = '([^']+)'",sw).group(1)
if sv!=wv: die(f'APP_VERSION mismatch: state={sv}, sw={wv}')

if 'assets/css/pro-workspace-v51.css' not in html: die('Professional UI v51 stylesheet not loaded')
css_refs=re.findall(r'<link[^>]+href=["\'](assets/css/[^"\']+)["\']',html)
if 'assets/css/timetable-v52-1.css' not in html: die('Timetable v52.1 stylesheet not loaded')
if 'assets/css/plan-revision-v51.css' not in html: die('Plan revision stylesheet not loaded')
if not css_refs or css_refs[-1] != 'assets/css/plan-revision-v51.css': die('Plan revision stylesheet must load last')
if css_refs.index('assets/css/pro-workspace-v51.css') > css_refs.index('assets/css/plan-revision-v51.css'): die('Professional UI must load before plan revision overrides')
if css_refs.index('assets/css/timetable-v52-1.css') < css_refs.index('assets/css/pro-workspace-v51.css'): die('Timetable v52.1 overrides must load after Professional UI')
if css_refs.index('assets/css/timetable-v52-1.css') > css_refs.index('assets/css/plan-revision-v51.css'): die('Timetable v52.1 stylesheet must load before final plan-revision overrides')
timetable_js=(ROOT/'assets/js/12-timetable.js').read_text(encoding='utf-8')
if 'function buildTimetableLessonPreviewMap' not in timetable_js: die('Missing timetable PPCT preview map helper')
if 'data-tt-detail=' not in timetable_js: die('Timetable cells do not expose PPCT detail tooltip data')
timetable_css=(ROOT/'assets/css/timetable-v52-1.css').read_text(encoding='utf-8')
if 'tbody tr:nth-child(even) td.period-cell' not in timetable_css: die('Timetable period-cell zebra override missing')
if '.timetable-lesson-tooltip' not in timetable_css: die('Timetable lesson tooltip style missing')
if not (ROOT/'assets/js/27-regression-tests.js').exists(): die('Regression module file missing')
if 'assets/js/28-gradebook.js' not in p.scripts: die('Personal gradebook module not loaded in index.html')
if 'assets/js/29-homeroom.js' not in p.scripts: die('Personal homeroom module not loaded in index.html')
if p.scripts.index('assets/js/28-gradebook.js') >= p.scripts.index('assets/js/15-init.js'): die('Gradebook module must load before init')
if p.scripts.index('assets/js/29-homeroom.js') >= p.scripts.index('assets/js/15-init.js'): die('Homeroom module must load before init')
if 'assets/css/gradebook-v51.css' not in html: die('Personal gradebook stylesheet not loaded')
if 'assets/css/homeroom-v51.css' not in html: die('Personal homeroom stylesheet not loaded')
if 'assets/css/homeroom-v52-2.css' not in html: die('Homeroom v52.2 monitoring stylesheet not loaded')
if 'assets/css/homeroom-v52-3.css' not in html: die('Homeroom v52.3 conduct score stylesheet not loaded')
if 'assets/css/homeroom-v52-4.css' not in html: die('Homeroom v52.4 priority/trend stylesheet not loaded')
if 'assets/css/release-v52-5.css' not in html: die('v52.5 Today experience stylesheet not loaded')
if 'homeroomAttentionList' not in ids or 'todayFocusBtn' not in ids: die('v52.5 Today command-center controls missing')
if 'function renderHomeroomAttentionCommand' not in js: die('v52.5 homeroom attention command helper missing')
if 'body.teacher-focus-mode #teacherCommandCenter{display:none!important}' in (ROOT/'assets/css/release-v52.css').read_text(encoding='utf-8'): die('Focus mode must keep Today command center visible')
if "const GRADEBOOK_MAX_REGULAR_COLUMNS = 5;" not in js: die('Gradebook must cap regular assessment columns at 5')
if 'gradebook: normalizeGradebookWorkspace(source.gradebook)' not in state: die('Year workspace does not persist personal gradebook')
if 'homeroom: normalizeHomeroomWorkspace(source.homeroom)' not in state: die('Year workspace does not persist personal homeroom notebook')
if 'monitoringThresholds: normalizeHomeroomMonitoringThresholds(value.monitoringThresholds)' not in state: die('Homeroom monitoring thresholds are not persisted')
if 'function homeroomStudentMetrics' not in js or 'function homeroomStudentMonitoringStatus' not in js: die('Homeroom frequent-behavior monitoring helpers missing')
if 'homeroomMonitoringTable' not in ids: die('Homeroom monitoring table missing from HTML')
if 'homeroomConductRuleSelect' not in ids or 'homeroomWeekAnchorDate' not in ids: die('Homeroom v52.3 conduct/weekly score controls missing')
if 'const HOMEROOM_CONDUCT_RULES = [' not in js or "id:'fight'" not in js or 'points:-25' not in js: die('Homeroom v52.3 conduct rules missing or fight penalty not protected')
if 'function homeroomStudentTrend' not in js or 'activeSeriousCount' not in js or 'resolvedSeriousCount' not in js: die('Homeroom v52.4 priority/trend helpers missing')
if 'homeroomImprovingCount' not in ids or 'homeroomDecliningCount' not in ids: die('Homeroom v52.4 trend KPI controls missing')
if "seriousFlag: Boolean(value.seriousFlag) || severity === 'critical'" not in state: die('Critical conduct flag is not persisted independently from points')
account_js=(ROOT/'assets/js/04-account-firestore.js').read_text(encoding='utf-8')
if 'gradebook: normalized.gradebook' not in account_js: die('Personal cloud payload does not include gradebook')
if 'homeroom: normalized.homeroom' not in account_js: die('Personal cloud payload does not include homeroom notebook')
backup_js=(ROOT/'assets/js/05-backup-restore.js').read_text(encoding='utf-8')
if 'homeroom: state.homeroom' not in backup_js or 'normalizeHomeroomWorkspace(data.homeroom' not in backup_js: die('Backup/Restore does not include homeroom notebook')

if 'assets/js/11-plan-revision.js' not in p.scripts: die('Plan revision module not loaded in index.html')
if p.scripts.index('assets/js/11-plan-revision.js') >= p.scripts.index('assets/js/11-plan.js'): die('Plan revision module must load before plan module')
plan_js=(ROOT/'assets/js/11-plan.js').read_text(encoding='utf-8')
if 'reviewPlanRevision(existing, plan' not in plan_js: die('Plan upload does not review same-week revisions')
if "state.planData[existingIndex] = plan" in plan_js: die('Unsafe direct overwrite of existing weekly plan still present')
if 'planRevisionFingerprint(currentPlan) !== review.baseFingerprint' not in plan_js: die('Plan revision concurrency guard missing')
if 'assets/js/04-shared-core.js' not in p.scripts: die('Shared core module not loaded in index.html')
if p.scripts.index('assets/js/04-shared-core.js') <= p.scripts.index('assets/js/04-account-firestore.js'): die('Shared core must load after account/firestore helpers')
if p.scripts.index('assets/js/04-shared-core.js') >= p.scripts.index('assets/js/05-backup-restore.js'): die('Shared core must load before backup/restore')
if 'assets/js/32-module-loader.js' not in p.scripts: die('v52.6 feature module loader missing')
if any('assets/js/'+name in p.scripts for name in ['19-report-center.js','21-health-check.js','22-links-center.js','24-storage-center.js','25-profile-package.js','27-regression-tests.js']): die('v52.6 optional modules must not block initial HTML')
if p.scripts[-1] != 'assets/js/15-init.js': die('15-init.js must remain last internal script')
listener_count=len(re.findall(r"window\.addEventListener\(['\"]teacher-data-changed['\"]",js))
if listener_count != 1: die(f'teacher-data-changed should have one shared listener, found {listener_count}')
minute_timer_count=len(re.findall(r"setInterval\([^\n]*60000",js))
if minute_timer_count != 1: die(f'60-second UI heartbeat should be centralized, found {minute_timer_count}')
if 'function buildPpctAlerts' in js: die('PPCT reminder must not have a separate suggestion engine')
if 'function buildProgressAttentionSnapshot' not in js: die('Missing shared PPCT progress snapshot helper')
if 'function addWorkSystemSuggestion' not in js: die('Missing generic system-suggestion saver')
if 'PPCT alert may not originate from the standard suggestion cache' in js: die('Legacy PPCT direct-save fallback still present')
if 'function getSmartReminderManagedSuggestionKeys' not in js: die('Missing Reminder/Suggestion de-duplication helper')
if '.filter(isSystemSuggestionReminderWorthy).map(suggestion =>' not in js: die('System Reminder must filter to high/urgent suggestions before rendering')
if 'workSuggestionCache = allSuggestions.filter(item => !reminderManagedKeys.has(item.key));' not in js: die('Work suggestions do not exclude Reminder-managed items')
if js.count('<p>${esc(alert.detail)}</p>') != 1: die('Reminder detail markup should be rendered once')
if 'function getSchoolSemesterInfo' not in js: die('Missing semester boundary helper')
if 'function getCurriculumSemesterTargets' not in js: die('Missing curriculum semester target helper')
if 'function detectSemesterOneEndSuggestion' not in js: die('Missing HKI boundary suggestion helper')
if 'semesterOneEndPpct' not in js: die('Missing teacher-confirmed HKI boundary field')
if 'sourceWeek > 0 && sourceWeek <= SEMESTER_ONE_END_WEEK' in js: die('Legacy HKI boundary inference from sourceWeek is still present')
if 'function buildSemesterForecastMetrics' not in js: die('Missing semester forecast helper')
if 'function buildSemesterRemainingStatus' not in js: die('Missing semester remaining-status helper')
if 'const TOTAL_ACADEMIC_CALENDAR_WEEKS = MAX_SCHOOL_WEEKS + MAX_AUXILIARY_WEEKS;' not in js: die('Missing 39-week academic calendar invariant')
if 'function getAcademicCalendarWeekSequence' not in js: die('Missing 39-week calendar sequence helper')
if 'statusLabel = `Chậm ${Math.abs(difference)} tiết`' in js: die('Legacy user-facing Chậm x tiết status still present')
if 'Nguy cơ đến tuần ${forecastWeek}' in js: die('Legacy annual forecast label still present')
if 'nguy cơ chưa hoàn thành trước tuần ${MAX_SCHOOL_WEEKS}' in js: die('Legacy whole-year risk notice still present')
print(f'PASS: HTML IDs {len(p.ids)}/{len(set(p.ids))} unique')
print(f'PASS: HTML resources {len(p.refs)} present')
print(f'PASS: DOM refs {len(domrefs)} resolved')
print(f'PASS: named functions {len(fn)}/{len(set(fn))} unique')
print(f'PASS: APP_SHELL {len(app_shell)} resources present')
print(f'PASS: APP_VERSION {sv}')
print('PASS: Professional UI + timetable v52.1 + plan revision styles load in safe order')
print('PASS: timetable periods 1–5 protected from zebra/hover overrides and PPCT tooltip wired')
print('PASS: personal gradebook loaded, private workspace persisted, TX columns capped at 5')
print('PASS: personal homeroom notebook loaded and private workspace persisted')
print('PASS: homeroom v52.2 frequency monitoring thresholds + dashboard wired')
print('PASS: homeroom v52.3 weekly conduct points + repeat multiplier + critical flag wired')
print('PASS: homeroom v52.4 resolved-serious history + 4-week trends + GVCN priority wired')
print('PASS: v52.5 Today command center + homeroom attention + focus-mode wiring')
if not (ROOT/'assets/js/33-browser-smoke.js').exists() or not (ROOT/'tests/browser-smoke.html').exists(): die('v52.7 browser smoke suite missing')
if 'runBrowserSmokeBtn' not in ids: die('v52.7 browser smoke launcher missing')
print('PASS: v52.6 optional feature modules load on demand/idle')
if 'assets/js/34-safety-snapshots.js' not in p.scripts: die('v52.8 safety snapshot module must load before init')
if p.scripts.index('assets/js/34-safety-snapshots.js') >= p.scripts.index('assets/js/15-init.js'): die('v52.8 safety snapshot module must load before init')
if not {'createSafetySnapshotBtn','restoreSafetySnapshotBtn','safetySnapshotSummary'}.issubset(ids): die('v52.8 safety snapshot controls missing')
if 'SAFETY_LIMIT = 5' not in js or 'SAFETY_INTERVAL_MS = 12 * 60 * 60 * 1000' not in js: die('v52.8 safety retention/interval invariant missing')
print('PASS: v52.7 browser smoke suite + launcher wired')
if 'ACCOUNT_SYNC_OUTBOX_STORAGE' not in account_js or 'markAccountSyncOutbox' not in account_js or "window.addEventListener('online', handleAccountNetworkOnline)" not in account_js: die('v52.9 resilient cloud sync outbox/reconnect wiring missing')
if "Mất mạng · sẽ tự đồng bộ khi có mạng" not in account_js: die('v52.9 offline sync state missing')
print('PASS: v52.8 automatic 12h safety snapshots + restore controls wired')
if 'assets/js/35-stable-guard.js' not in p.scripts: die('v53.0 stable boot guard missing from initial HTML')
if p.scripts.index('assets/js/35-stable-guard.js') != 0: die('v53.0 stable boot guard must be first internal script')
if not (ROOT/'release-manifest.json').exists(): die('v53.0 release manifest missing')
import json
release_manifest=json.loads((ROOT/'release-manifest.json').read_text(encoding='utf-8'))
if release_manifest.get('release') != sv or release_manifest.get('channel') != 'stable': die('v53.0 release manifest version/channel mismatch')
if 'teacherNotebookStableGuard?.safeMode' not in (ROOT/'assets/js/32-module-loader.js').read_text(encoding='utf-8'): die('v53.0 safe mode does not suppress idle optional modules')
print('PASS: v52.9 offline sync outbox + automatic reconnect flush wired')
print('PASS: v53.0 STABLE safe-boot guard + release manifest wired')
print(f'PASS: centralized data-change listeners {listener_count}')
print(f'PASS: centralized minute heartbeat {minute_timer_count}')
print('PASS: PPCT uses unified suggestion engine')
print('PASS: Reminder/System Suggestions de-duplicated')
print('PASS: semester forecast uses teacher-confirmed HKI boundary')
print('PASS: progress status shows remaining periods by semester')
print('PASS: academic calendar supports 39 weeks (2 auxiliary + 37 main)')
print('PASS: same-week plan uploads use guarded revision comparison')
print('PASS: all JavaScript node --check')
